2020-06-22 14:43:01,502| ERROR 
Queryable.In(params object[] pkValues): Only one primary key
【自定义错误】：Queryable.In(params object[] pkValues): Only one primary key 
【异常类型】：SqlSugarException 
【异常信息】：Queryable.In(params object[] pkValues): Only one primary key 
【堆栈调用】：   at SqlSugar.Check.Exception(Boolean isException, String message, String[] args)
   at SqlSugar.QueryableProvider`1.In[TParamter](TParamter[] pkValues)
   at Funeral.Core.Repository.Base.BaseRepository`1.QueryById(Object objId)
   at Funeral.Core.Services.BASE.BaseServices`1.QueryById(Object objId)
   at Funeral.Core.AOP.InternalAsyncHelper.AwaitTaskWithPostActionAndFinallyAndGetResult[T](Task`1 actualReturnValue, Func`2 postAction, Action`1 finalAction) in D:\旧文件\TestPro\新建文件夹\Blog.Core-master\Funeral.Core\AOP\FuneralLogAOP.cs:line 195
   at Funeral.Core.Controllers.TenanController.GetById(Int32 tid) in D:\旧文件\TestPro\新建文件夹\Blog.Core-master\Funeral.Core\Controllers\TenanController.cs:line 164
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
--------------------------------
2020-06-22 14:45:09,594| ERROR 
Queryable.In(params object[] pkValues): Only one primary key
【自定义错误】：Queryable.In(params object[] pkValues): Only one primary key 
【异常类型】：SqlSugarException 
【异常信息】：Queryable.In(params object[] pkValues): Only one primary key 
【堆栈调用】：   at SqlSugar.Check.Exception(Boolean isException, String message, String[] args)
   at SqlSugar.QueryableProvider`1.In[TParamter](TParamter[] pkValues)
   at Funeral.Core.Repository.Base.BaseRepository`1.QueryById(Object objId)
   at Funeral.Core.Services.BASE.BaseServices`1.QueryById(Object objId)
   at Funeral.Core.AOP.InternalAsyncHelper.AwaitTaskWithPostActionAndFinallyAndGetResult[T](Task`1 actualReturnValue, Func`2 postAction, Action`1 finalAction) in D:\旧文件\TestPro\新建文件夹\Blog.Core-master\Funeral.Core\AOP\FuneralLogAOP.cs:line 195
   at Funeral.Core.Controllers.TenanController.GetById(Int32 tid) in D:\旧文件\TestPro\新建文件夹\Blog.Core-master\Funeral.Core\Controllers\TenanController.cs:line 161
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
--------------------------------
